language: generic
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
env:
  global:
    secure: PNJfSm0Pc/+b13U8ypIpnlTwUEyOlWvpgY3eyKhbtcdbyJ8hq/lIj6z5XoBXmky3Jy7+2dL6595NcnMr6B4lo2O3otS11ci9OvAcnpQBHDDMteAiRXKx+BiqlHMXa0dYztjBgvlXPZxYfSu4ahZaGNC1r6BEi5uE2wv2D3xWzf6fKo6RRkgVm5RvdPgApVSr0vdG65SdU1OQ0CY0y1dTunP52e/KgkoRK1W7ogLXk0Mp/xtdFKqCgR4wD+5L+ZSn9MR6/Ffd03X33ErvCJUNy/XAx1H5fKpysgFy3Y2/s+SCarhRsdgK1iesdobf+xwQs6IBY3YLzMYsx12ERn5zsO2y/nYpujNXN49rgKAlPke40oYW41jK5n8Py7RhgmIR13wdelbSCRm7DrZrqFsV2TQc0QGPYmddw/il51RsqmfQyNdN2pC9i62RoAEiKPhkuIpcAL3gp2PiyW5FHEj073ktppwsZDUl4R4g5/u0gCO8gi5U5DiGOncu1onhU71HTt0gYEg+a6FRkbGNbgKR2psCYq51P24HAeXAi8XF1YjCUqRDGcnhbpUw1tvQdExvhF/tSN1jbMuqSU6u5oLc6qKeJ9Kjr3TtfxGLN+h2Ayh4QWtnSDmSApa0ovJmLMS2zOMFcYpBC+kjKM8jlJMvtjZ97aza9Du5JLgenLX1t+A=
