
language: generic

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
  secure: "p58OZvscZHV2UH3T+vJANLNKe8I5/DL4nJsjGgf22w6Ut2fw41F9JvVG2ZH6yusgkNul9LeUZrY8nOkM4CptvQs4M35lVZJr21wjGD1T2OAJOhcmAIB2N1BYXpjB1DSMX0DXscR2Ca04cR5dngWjb/FfAioNxq3vzQIwRuVtcBZsTJH+sgR3kEKmD9by4Rh6ktXNO+KkuQPJyKPTeQgDsjSy2hk8U7hpyp+h7f4XV5/brizcjXZjqUP/UwUmtX6yzVk3S0B3JJp2h6wIP5/Th/KbID/GhM9D0uZpwul+O36x6YBrzVy2XTnpITPjYl1PP+V0zdZRQQ6H/Q4AXNGV0gFn8TgwVRezCgJ+Mx4c5gPWUqEcNI6yEQZGHvJ3I/UQMDVZZL3NzYHM0mvU3uRHqO8eFXEK9gaBJV7xa2FctLmnfyivRUjDdZtfQ9qOWshpIuHSC6KsiGPOAPkcOl1M8/7PHnmF7gFl4u4r2NsC1JAXyVviqxDQ02byIfm68EuPnQl87Vkdf0OdcS085tkYWOFHdjk3AqGqiw7wm3FmdTMKiIYa0tpiDE0/NHfZ0E+PBRh4GoiULRVW5Tc16VUznjH6dzgOz5cd+0mEWyT3WcYmj4ffX1fyoF5bq/Mv8h5BZo88Vaj04qQPd/xeoya00pG/qKIs57q/0jSeG96Kxv4="
